# Generated by Django 4.1.7 on 2023-03-31 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_memberteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberteam',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.teams'),
        ),
    ]
