# Generated by Django 4.1.7 on 2023-05-15 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_representativesorganizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representativesorganizations',
            name='organization_number',
            field=models.ForeignKey(db_column='number', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.participatingorganizations'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='moderator_number',
            field=models.ForeignKey(blank=True, db_column='Moderator number', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.moderators'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='number',
            field=models.ForeignKey(blank=True, db_column='Task number', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.tasks'),
        ),
    ]
