# Generated by Django 4.1.7 on 2023-05-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_representativesorganizations_organization_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='number',
            new_name='task_id',
        ),
        migrations.RemoveField(
            model_name='participatingorganizations',
            name='letter_number',
        ),
        migrations.DeleteModel(
            name='InvitedOrganizations',
        ),
    ]
