# Generated by Django 4.1.7 on 2023-04-05 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberteam',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teams',
            name='task_id',
            field=models.ForeignKey(blank=True, db_column='Task number', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.tasks'),
        ),
    ]
