# Generated by Django 4.1.7 on 2023-05-27 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_number_teams_task_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participatingorganizations',
            name='manager_name',
        ),
        migrations.RemoveField(
            model_name='participatingorganizations',
            name='manager_patronymic',
        ),
        migrations.RemoveField(
            model_name='participatingorganizations',
            name='manager_surname',
        ),
        migrations.RemoveField(
            model_name='representativesorganizations',
            name='organization_number',
        ),
        migrations.AddField(
            model_name='participatingorganizations',
            name='manager',
            field=models.ForeignKey(db_column='Manager', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.representativesorganizations'),
        ),
    ]
