# Generated by Django 4.1.7 on 2023-05-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_participatingorganizations_manager_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='link_to_the_task_text',
        ),
        migrations.AddField(
            model_name='tasks',
            name='description',
            field=models.CharField(db_column='Description', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='input_data',
            field=models.CharField(db_column='Input data', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='purpose',
            field=models.CharField(db_column='Purpose', max_length=100, null=True),
        ),
    ]
