# Generated by Django 4.1.7 on 2023-04-05 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_memberteam_user_alter_teams_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='task_id',
            field=models.ForeignKey(blank=True, db_column='Task number', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.tasks'),
        ),
    ]
