# Generated by Django 4.1.7 on 2023-05-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_tasks_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participatingorganizations',
            name='description',
            field=models.CharField(db_column='Description', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.CharField(db_column='Description', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='purpose',
            field=models.CharField(db_column='Purpose', max_length=1000, null=True),
        ),
    ]
